Code/account/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from .views import *

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^register/student/$', StudentRegisterView.as_view()),
    url(r'^register/not-student/$', NotStudentRegisterView.as_view()),
    url(r'^issue-borrowing-card/$', IssueBorrowingCardView.as_view(), name='issue-borrowing-card'),
    url(r'^activate-borrowing-card/$', ActivateBorrowingCardView.as_view(), name='activate-borrowing-card'),
    url(r'^denied/$', DeniedView.as_view(), name='denied'),
]

Code/book/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from .views import *

urlpatterns = [
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^backdoor/$', BackdoorRegisterView.as_view(), name='backdoor'),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^detail/(?P<pk>\d+)/$', DetailView.as_view(), name='detail'),
]

Code/config/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^', include('account.urls', namespace='account')),
    url(r'^book/', include('book.urls', namespace='book')),
    url(r'^transaction/', include('transaction.urls', namespace='transaction')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Code/transaction/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from .views import *

urlpatterns = [
    url(r'^cart/$', CartView.as_view(), name='cart'),
    url(r'^clear-cart/$', ClearCartView.as_view(), name='clear-cart'),
    url(r'^add-to-cart/$', AddToCartView.as_view(), name='add-to-cart'),
    url(r'^check-out/$', CheckOutView.as_view(), name='check-out'),
    url(r'^borrow/$', BorrowView.as_view(), name='borrow'),
    url(r'^lent/$', LentView.as_view(), name='lent'),
    url(r'^history/$', HistoryView.as_view(), name='history'),
    url(r'^return/$', ReturnView.as_view(), name='return'),
]

Code/templates/home.html
{% extends "includes/layout.html" %}

{% load static %}
{% load humanize %}
{% load mathfilters %}

{% block breadcrumb %}
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb">
                <li><a href="{% url 'account:index' %}">Home</a></li>
                {% if librarian %}
                    <li><a href="{% url 'account:issue-borrowing-card' %}">Issue Borrowing Card</a></li>
                    <li><a href="{% url 'book:register' %}">Register Book or Copies</a></li>
                    <li><a href="{% url 'transaction:lent' %}">Lent books</a></li>
                    <li><a href="{% url 'transaction:return' %}">Receive books</a></li>
                {% elif user.is_authenticated %}
                    <li><a href="{% url 'account:activate-borrowing-card' %}">Your Borrowing Card</a></li>
                    <li><a href="{% url 'transaction:check-out' %}">Check Out</a></li>
                    <li><a href="{% url 'transaction:borrow' %}">Borrowed list</a></li>
                {% endif %}

            </ol>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="row">
            </div>
          <!-- /.row -->
            {% if home_books %}
                <div class="row">
                    <div style="text-align:center;">Total {{ count }} home_books</div>
                </div>
                {% for row in home_books %}
                    <div class="row">
                        {% for book in row %}
                            <div class="col-lg-4" style="margin: 15px 0">
                                <p> <strong>Title</strong>: {{ book.title }} </p>
                                <p> <strong>Authors</strong>: {{ book.authors }}</p>
                                <a href="{% url 'book:detail' book.id %}">
                                    <img src="/media/{{ book.cover }}"/>
                                </a>              
                            </div>
                            {% endfor %}
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock %}