Code/account/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from .views import *

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^register/student/$', StudentRegisterView.as_view()),
    url(r'^register/not-student/$', NotStudentRegisterView.as_view()),
    url(r'^issue-borrowing-card/$', IssueBorrowingCardView.as_view(), name='issue-borrowing-card'),
    url(r'^activate-borrowing-card/$', ActivateBorrowingCardView.as_view(), name='activate-borrowing-card'),
    url(r'^denied/$', DeniedView.as_view(), name='denied'),
]

Code/book/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from .views import *

urlpatterns = [
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^backdoor/$', BackdoorRegisterView.as_view(), name='backdoor'),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^detail/(?P<pk>\d+)/$', DetailView.as_view(), name='detail'),
]

Code/config/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^', include('account.urls', namespace='account')),
    url(r'^book/', include('book.urls', namespace='book')),
    url(r'^transaction/', include('transaction.urls', namespace='transaction')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Code/transaction/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from .views import *

urlpatterns = [
    url(r'^cart/$', CartView.as_view(), name='cart'),
    url(r'^clear-cart/$', ClearCartView.as_view(), name='clear-cart'),
    url(r'^add-to-cart/$', AddToCartView.as_view(), name='add-to-cart'),
    url(r'^check-out/$', CheckOutView.as_view(), name='check-out'),
    url(r'^borrow/$', BorrowView.as_view(), name='borrow'),
    url(r'^lent/$', LentView.as_view(), name='lent'),
    url(r'^history/$', HistoryView.as_view(), name='history'),
    url(r'^return/$', ReturnView.as_view(), name='return'),
]

Code/templates/includes/footer.html
<div class="container">

    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; lethanh 2017</p>
            </div>
        </div>
    </footer>

</div>
<!-- /.container -->

{% load static %}

<!-- jQuery -->
<script src="{% static 'js/jquery.js' %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'js/bootstrap.min.js' %} "></script>

Code/templates/includes/head.html
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ISD - Library</title>

    {% load static %}

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/shop-homepage.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

Code/templates/includes/layout.html
<!DOCTYPE html>
<html lang="en">
{% include "includes/head.html" %}
<body>
    {% include "includes/nav.html" %}
    <div class="container">
        {% block breadcrumb %}{% endblock %}
        <div class="row">
            {% if error %}
            <div class="alert alert-danger alert-dismissible" role="alert">
                <button class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
                <strong>{{ error }}</strong>
            </div>
            {% elif success %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <button class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
                <strong>{{ success }}</strong>
            </div>
            {% endif %}
        </div>
        {% block content %}{% endblock %}
    </div>
    {% include "includes/footer.html" %}
</body>

Code/templates/includes/nav.html
{% load static %}

<!-- Navigation -->
<nav class="navbar navbar-light navbar-fixed-top" style="background-color: #e3f2fd;" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'account:index' %}" style="color: #000;">ISD Library</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <div class="collapse navbar-collapse">
                <form class="navbar-form navbar-left" role="search" action="{% url 'book:search' %}" method="get">
                    <div class="form-group">
                        <input type="text" class="form-control" name="query" placeholder="Enter any keyword">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>
                <ul class="nav navbar-nav" style="float: right;">
                    {% if user.is_authenticated %}
                        <li class="navbar-text navbar-left">Logged in as
                        {% if librarian %}
                            <strong>librarian</strong>
                        {% else %}
                            <strong>user</strong>
                        {% endif %}
                         {{ user.username }}</li>
                        <li>
                            <a href="{% url 'account:logout' %}">Logout</a>
                        </li>
                        <li>
                            <a href="{% url 'transaction:cart' %}">
                                <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> Cart
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'transaction:history' %}">
                                <span class="glyphicon glyphicon-list" aria-hidden="true"></span> Transaction History
                            </a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'account:login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'account:register' %}">Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>


        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>