Code/book/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from .views import *

urlpatterns = [
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^backdoor/$', BackdoorRegisterView.as_view(), name='backdoor'),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^detail/(?P<pk>\d+)/$', DetailView.as_view(), name='detail'),
]

Code/config/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^', include('account.urls', namespace='account')),
    url(r'^book/', include('book.urls', namespace='book')),
    url(r'^transaction/', include('transaction.urls', namespace='transaction')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Code/transaction/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from .views import *

urlpatterns = [
    url(r'^cart/$', CartView.as_view(), name='cart'),
    url(r'^clear-cart/$', ClearCartView.as_view(), name='clear-cart'),
    url(r'^add-to-cart/$', AddToCartView.as_view(), name='add-to-cart'),
    url(r'^check-out/$', CheckOutView.as_view(), name='check-out'),
    url(r'^borrow/$', BorrowView.as_view(), name='borrow'),
    url(r'^lent/$', LentView.as_view(), name='lent'),
    url(r'^history/$', HistoryView.as_view(), name='history'),
    url(r'^return/$', ReturnView.as_view(), name='return'),
]

Code/transaction/models/History.py
from account.models import *
from book.models import *
from django.db import models

TYPES = (('B', 'Borrow'), ('L', 'Lent'))

class History(models.Model):

    type = models.CharField(max_length=2, choices=TYPES)
    start = models.DateField()
    end = models.DateField(auto_now=True, null=True)
    card = models.ForeignKey(Card)
    copy = models.ForeignKey(Copy)
    description = models.TextField()

Code/transaction/models/Transaction.py
from account.models import *
from book.models import *
from django.db import models
from django.core.exceptions import ValidationError
import datetime

TYPES = (('B', 'Borrow'), ('L', 'Lent'))

class Transaction(models.Model):

    type = models.CharField(max_length=2, choices=TYPES)
    start = models.DateField(auto_now=True)
    card = models.ForeignKey(Card)
    copy = models.OneToOneField(Copy, unique=True)

    def get_due(self):
        setting = Setting.load()
        if self.type == 'B':
            return self.start + datetime.timedelta(days=setting.borrow_expire)
        elif self.type == 'L':
            return self.start + datetime.timedelta(days=setting.lent_due)

    def clean_card(self):
        setting = Setting.load()
        if self.objects.filter(card=self.card).count() >= setting.maximum_book_borrow:
            raise ValidationError('Exceed maximum number of copies per card')
        return self.card

Code/transaction/forms/AddToCartForm.py
from ..models import *
from book.models import *
from django import forms
from django.core.exceptions import ValidationError

class AddToCartForm(forms.Form):

    book_id = forms.IntegerField(widget=forms.HiddenInput(), required=False)

    def clean_book_id(self):
        book_id = self.cleaned_data['book_id']
        try:
            book = Book.objects.get(id=book_id)
        except Book.DoesNotExist:
            raise ValidationError('Book is not existed')
        else:
            for copy in Copy.objects.filter(book=book, type='A'):
                if not Transaction.objects.filter(copy=copy).exists():
                    return {'book_id': book_id, 'copy_id': copy.id}
            raise ValidationError('Book is not avalable')

Code/transaction/forms/CompensationForm.py
from ..models import *
from django import forms
from django.core.exceptions import ValidationError

class CompensationForm(forms.Form):
    compensation_percentage = forms.IntegerField(initial=0)

    def clean_compensation_percentage(self):
        compensation_percentage = self.cleaned_data['compensation_percentage']
        if compensation_percentage < 0:
            raise ValidationError('Compensation percentage cannot be negative')
        if compensation_percentage > 100:
            raise ValidationError('Compensation percentage cannot be greater than 100')
        return compensation_percentage

Code/transaction/forms/CompensationVerifyForm.py
from ..models import *
from django import forms
from django.core.exceptions import ValidationError

class CompensationVerifyForm(forms.Form):

    paid = forms.BooleanField()

    def clean_paid(self):
        paid = self.cleaned_data['paid']
        if not paid:
            raise ValidationError('Borrower must paid compensation money')
        return paid

Code/transaction/forms/LentForm.py
from ..models import *
from django import forms
from django.core.exceptions import ValidationError

class LentForm(forms.Form):

    def __init__(self, transactions, *args, **kwargs):
        super(LentForm, self).__init__(*args, **kwargs)
        CHOICES = tuple([(
            transaction.id, 
            transaction.copy.book.title + 
            '(copy sequential number: ' + str(transaction.copy.sequential_number) + 
            ')(price: ' + str(transaction.copy.price) + ' VND)' ) for transaction in transactions])
        self.fields['transactions'] = forms.TypedMultipleChoiceField(choices=CHOICES, widget=forms.CheckboxSelectMultiple)
        self.fields['accept'] = forms.BooleanField(
            help_text='Only check this if you can guarantee user pay enough money and user information is correct')

    def clean_accept(self):
        paid = self.cleaned_data['accept']
        if not paid:
            raise ValidationError('You did not accept this transaction')
        return paid

Code/transaction/forms/SearchBorrowInformationForm.py
from ..models import *
from account.models import *
from django import forms
from django.core.exceptions import ValidationError

class SearchBorrowInformationForm(forms.Form):

    username = forms.CharField()

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            raise ValidationError('username does not exist')
        else:
            try:
                card = Card.objects.get(user=user)
            except Card.DoesNotExist:
                raise ValidationError('user does not have borrowing card')
            else:
                if not card.is_activated:
                    raise ValidationError('user has an inactive borrowing card')
                return username

Code/transaction/forms/SearchLentInformationForm.py
from ..models import *
from django import forms
from book.models import *
from account.models import *
from django.core.exceptions import ValidationError

class SearchLentInformationForm(forms.Form):

    card_id = forms.IntegerField(required=False)
    copy_id = forms.IntegerField(required=False)

    def clean_card_id(self):
        card_id = self.cleaned_data['card_id']
        if card_id and not Card.objects.filter(id=card_id).exists():
            raise ValidationError('Card does not exist')
        return card_id

    def clean_copy_id(self):
        copy_id = self.cleaned_data['copy_id']
        if copy_id and not Copy.objects.filter(id=copy_id).exists():
            raise ValidationError('Copy does not exist')
        return copy_id

Code/transaction/views/AddToCartView.py
from ..models import *
from ..forms import *
from django.views import View
from django.utils.decorators import method_decorator
from django.template.response import TemplateResponse
from django.contrib.auth.decorators import login_required

@method_decorator([login_required(login_url='/login/')], name='dispatch')
class AddToCartView(View, CartSmartProxy):
    '''
    Borrowers may register to borrow books after browsing catalog and selecting some books to be
    borrowed. A borrower cannot borrow books if his/her borrower card is expired or he/she still
    borrowed any overdue unreturned books. The status of each copy indicates it is available,
    referenced, borrowed (not lend physically to borrowers) or lent (lend physically to borrowers).
    Only the available copy is allowed to be borrowed.
    '''
    template_name = 'transaction/cart.html'

    def get(self, request):
        '''
        Return add to cart form to borrower

        :param request: HTTP GET request to this view
        :type request: :class:`django.http.HttpRequest`

        :returns: :class:`django.template.response.TemplateResponse`, 
                  contain request, path to template file, and context

                  context include :class:`transaction.forms.AddToCartForm()`
        '''
        add_to_cart_form = AddToCartForm()
        context = {'add_to_cart_form': add_to_cart_form}
        return TemplateResponse(request, self.template_name, context)

    def post(self, request):
        '''
        Receive add to cart form data from user and check multiple condition

        :param request: HTTP POST request to this view, contain :class:`transaction.forms.AddToCartForm()` form data
        :type request: :class:`django.http.HttpRequest`

        :returns: :class:`django.template.response.TemplateResponse`, 
                  contain request, path to template file, and context

                  context include error message if any requirement is not satisfy, otherwise return an success message
        '''
        add_to_cart_form = AddToCartForm(request.POST)

        if add_to_cart_form.is_valid():
            book = add_to_cart_form.cleaned_data['book_id']

            # Stage 1:
            if not self.has_card(request.user):
                context = {'error': 'You do not have borrowing card'}
                return TemplateResponse(request, self.template_name, context)
            # Stage 2:
            if self.card_expired(request.user):
                context = {'error': 'Your card is expired'}
                return TemplateResponse(request, self.template_name, context)
            # Stage 3:
            if self.in_possession(book, request):
                context = {'error': 'You already possess this book'}
                return TemplateResponse(request, self.template_name, context)
            # Stage 4:
            if self.still_borrow_overdue_books(request.user):
                context = {'error': 'You still must return overdue books to borrow more'}
                return TemplateResponse(request, self.template_name, context)
            # Stage 5:
            if self.exceed_max_copies(request):
                context = {'error': 'Cart is full'}
                return TemplateResponse(request, self.template_name, context)
            # Okay, now save to cart
            self.save(request, book)
            context = {
                'add_to_cart_form': add_to_cart_form,
                'success': 'Successfully added %s to cart' % self.get_name(book)
            }
            return TemplateResponse(request, self.template_name, context)

        context = {'add_to_cart_form': add_to_cart_form}
        return TemplateResponse(request, self.template_name, context)

Code/transaction/views/BorrowView.py
from ..models import *
from account.models import *
from django.views import View
from django.utils.decorators import method_decorator
from django.template.response import TemplateResponse
from django.contrib.auth.decorators import login_required

@method_decorator([login_required(login_url='/login/')], name='dispatch')
class BorrowView(View):

    template_name = 'transaction/borrow.html'

    def get(self, request):
        try:
            card = Card.objects.get(user=request.user)
        except Card.DoesNotExist:
            context = {}
            return TemplateResponse(request, self.template_name, context)

        borrowed = []
        for transaction in Transaction.objects.filter(card=card):
            borrowed.append({
                'transaction': transaction,
                'copy': transaction.copy,
                'book': transaction.copy.book,    
            })
        context = {'user': request.user, 'borrowed': borrowed}
        return TemplateResponse(request, self.template_name, context)

Code/transaction/views/CartView.py
from ..models import *
from django.views import View
from django.utils.decorators import method_decorator
from django.template.response import TemplateResponse
from django.contrib.auth.decorators import login_required


@method_decorator([login_required(login_url='/login/')], name='dispatch')
class CartView(View, CartSmartProxy):
    template_name = 'transaction/cart.html'

    def get(self, request):
        context = {}
        return TemplateResponse(request, self.template_name, context)

Code/transaction/views/CheckOutView.py
from ..models import *
from ..forms import *
from book.models import *
from account.models import *
from datetime import date
from django.views import View
from django.utils.decorators import method_decorator
from django.template.response import TemplateResponse
from django.contrib.auth.decorators import login_required

@method_decorator([login_required(login_url='/login/')], name='dispatch')
class CheckOutView(View, CartSmartProxy):
    '''
    Borrower can click check out to officially submit borrowing request to the system
    '''
    template_name = 'transaction/cart.html'

    def get(self, request):
        '''
        Examine list of books and copies user has added to cart. Check whether they are available to officially borrow. If any condition is not met, display error message. Otherwise save borrowing record to database and display success message

        :param request: HTTP GET request to this view, contain cart information in session
        :type request: :class:`django.http.HttpRequest`

        :returns: :class:`django.template.response.TemplateResponse`, 
          contain request, path to template file, and context

          context include success or error message
        '''
        cart = request.session['cart']

        if len(cart) == 0:
            context = {'error': 'Your cart is empty'}
            return TemplateResponse(request, self.template_name, context)

        while len(cart) > 0:
            item = cart.pop(0)
            
            if not Book.objects.filter(id=item['book_id']).exists():
                context = {'error': 'Book with id %d is not exist anymore' % item['book_id']}
                return TemplateResponse(request, self.template_name, context)
            if not Copy.objects.filter(id=item['copy_id']).exists():
                context = {'error': 'Copy with id %d is not exist anymore' % item['copy_id']}
                return TemplateResponse(request, self.template_name, context)
            copy = Copy.objects.get(id=item['copy_id'])
            if copy.type != 'A':
                context = {'error': 'Copy with id %d is not available anymore' % item['copy_id']}
                return TemplateResponse(request, self.template_name, context)
            if Transaction.objects.filter(copy=copy).exists():
                context = {'error': 'Copy with id %d is not available anymore' % item['copy_id']}
                return TemplateResponse(request, self.template_name, context)

            Transaction.objects.create(
                type='B',
                start=date.today(),
                card=Card.objects.get(user=request.user),
                copy=copy,
            )

        request.session['cart'] = cart
        context = self.get_context(request)
        context['success'] = 'Successfully check out'
        return TemplateResponse(request, self.template_name, context)

Code/transaction/views/ClearCartView.py
from ..models import *
from django.views import View
from django.utils.decorators import method_decorator
from django.template.response import TemplateResponse
from django.contrib.auth.decorators import login_required

@method_decorator([login_required(login_url='/login/')], name='dispatch')
class ClearCartView(View, CartSmartProxy):
    template_name = 'transaction/cart.html'

    def get(self, request):
        self.clear(request)
        context = {'success': 'Successfully clear cart'}
        return TemplateResponse(request, self.template_name, context)
    
    def post(self, request):
        self.clear(request)
        context = {'success': 'Successfully clear cart'}
        return TemplateResponse(request, self.template_name, context)

Code/transaction/views/HistoryView.py
from ..models import *
from ..forms import *
from account.models import *
from datetime import date
from django.views import View
from django.utils.decorators import method_decorator
from django.template.response import TemplateResponse
from django.contrib.auth.decorators import login_required


@method_decorator([login_required(login_url='/login/')], name='dispatch')
class HistoryView(View):
    template_name = 'transaction/history.html'

    def get(self, request):
        try:
            card = Card.objects.get(user=request.user) 
        except Card.DoesNotExist:
            context = {'error': 'You have to go to librian to issue a borrowing card first'}
            return TemplateResponse(request, self.template_name, context)

        records = []
        for history in History.objects.filter(card=card):
            records.append({
                'history': history,
                'card': history.copy,
                'book': history.copy.book,    
            })                                               
        context = {
            'user': request.user, 
            'records': records,
        }
        return TemplateResponse(request, self.template_name, context)

Code/templates/transaction/borrow.html
{% extends 'home.html' %}

{% block content %}    

    <h2>Borrowed</h2>
    {% for item in borrowed %}
        <h4>Title: {{ item.book.title }} </h4>
        <a href="{% url 'book:detail' item.book.id %}">
            <img src="/media/{{ item.book.cover }}"/>
        </a>
        <p>Borrowed at: {{ item.transaction.start }}</p>
        <p>Copy id: {{ item.transaction.copy.id }} </p>
        <p>Status: 
            {% if item.transaction.type == "B" %}
                you've just borrowed this book, please to go to library to take it
            {% else %}
                the librarian already lent you this book, please remember to return it
            {% endif %}
        </p>
    {% endfor %}

{% endblock %}

Code/templates/transaction/cart.html
{% extends 'home.html' %}

{% block content %}

    {% if add_to_cart_form.non_field_errors %}
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">x</span>
        </button>
        <strong>{{ add_to_cart_form.non_field_errors }}</strong>
    </div>
    {% endif %}

    {% if add_to_cart_form.book_id.errors %}
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">x</span>
        </button>
        <strong>{{ add_to_cart_form.book_id.errors }}</strong>
    </div>
    {% endif %}

    <h2>Cart</h2>
    {% for book in carts %}
        <p> Title: {{ book.title }} </p>
        <p> Authors: {{ book.authors }}</p>
        <p> Copy id: {{ book.id }}</p>
        <a href="{% url 'book:detail' book.id %}">
            <img src="/media/{{ book.cover }}"/>
        </a>
    {% endfor %}

    <form method="post" action="{% url 'transaction:clear-cart' %}">{% csrf_token %}
        <button type="submit">Clear cart</button>
    </form>
{% endblock %}

Code/templates/transaction/history.html
{% extends 'home.html' %}

{% block content %}    

    <h2>History</h2>
    {% for record in records %}
        <h4>Title: {{ record.book.title }} </h4>
        <a href="{% url 'book:detail' record.book.id %}">
            <img src="/media/{{ record.book.cover }}"/>
        </a>
        <p>Time: {{ record.history.start }} - {{ record.history.end }}</p>
        <p>Copy sequential number: {{ record.history.copy.sequential_number }}
        <p>Copy id: {{ record.history.copy.id }} </p>
        <p>Description: {{ record.history.description }}
    {% endfor %}

    <p>{{ error }}</p>

{% endblock %}

Code/templates/transaction/lent.html
{% extends 'home.html' %}

{% block content %}    
    
    {% if search_borrowing_information_form %}
        <h2>Search borrow information</h2>
        <form method="post">{% csrf_token %}
            {{ search_borrowing_information_form.as_p }}
            <button type="submit">Search</button>
        </form>
    {% endif %}


    {% if lent_form %}
        <h2>Please check on books that you lent the user</h2>
        <form method="post">{% csrf_token %}
            {{ lent_form.as_p }}
            {% if borrow_user %}
                <h2>User information</h2>
                <p>Fullname: {{borrow_user.first_name}} {{borrow_user.last_name}}</p>
                <p>Email: {{borrow_user.email}}</p>
                <p>Contact: {{borrow_user.contact}}</p>
                {% if borrow_user.is_student %}
                    <p>Type: Student (user do not have to pay any borrowing fee)</p>
                    <p>Student id: {{ student.student_id }}
                {% else %}
                    <p>Type: Not student (user need to pay borrowing fee)</p>
                    <p>Citizen id: {{ not_student.citizen_id }}
                    <p>Total fee: {{ total }} VND </p>
                {% endif %}
            {% endif %}
            <button type="submit">Lent</button>
        </form>
    {% endif %}

{% endblock %}

Code/templates/transaction/return.html
{% extends 'home.html' %}

{% block content %}    
    
    {% if search_lent_information_form %}
        <h2>Search lent information</h2>
        <form method="post">{% csrf_token %}
            {{ search_lent_information_form.as_p }}
            <button type="submit">Search</button>
        </form>
    {% endif %}

    {% for verify_lent_information_form in verify_lent_information_forms%}
        <h2>Verify lent information of transaction {{ verify_lent_information_form.transaction_id }}</h2>
        <p> <strong>Book title startwith</strong>: {{ verify_lent_information_form.transaction.copy.book.title|slice:':10'|join:'' }}</p>
        <form method="post">{% csrf_token %}
            {{ verify_lent_information_form.form.as_p }}
            <button type="submit">Verify</button>
        </form>
    {% endfor %}

    {% if compensation_form %}
        <h2>Submit compensation money</h2>
        <form method="post">{% csrf_token %}
            {{ compensation_form.as_p }}
            <button type="submit">Submit</button>
        </form>
    {% endif %}

    {% if compensation_verify_form %}
        <h2>Submit compensation money</h2>
        <p><strong>Total amount of compensation money:</strong>{{ total_compensation_money }} VND</p>
        <form method="post">{% csrf_token %}
            {{ compensation_verify_form.as_p }}
            <button type="submit">Submit</button>
        </form>
    {% endif %}


{% endblock %}