Final Project/Code/account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^register/student/$', StudentRegisterView.as_view()),
    url(r'^register/not_student/$', NotStudentRegisterView.as_view()),
    url(r'^issue_borrowing_card/$', IssueBorrowingCardView.as_view(), name='issue_borrowing_card'),
    url(r'^activate_borrowing_card/$', ActivateBorrowingCardView.as_view(), name='activate_borrowing_card'),
]

Final Project/Code/book/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^backdoor/$', BackdoorRegisterView.as_view()),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^detail/(?P<pk>\d+)/$', DetailView.as_view(), name='detail'),
    url(r'^copy/$', CopyView.as_view(), name='copy'),
]

Final Project/Code/transaction/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
    url(r'^add_to_cart/$', AddToCartView.as_view(), name='add_to_cart'),
    url(r'^clear_cart/$', ClearCartView.as_view(), name='clear_cart'),
    url(r'^cart/$', CartView.as_view(), name='cart'),
    url(r'^check_out/$', CheckOutView.as_view(), name='check_out'),
    url(r'^borrow/$', BorrowView.as_view(), name='borrow'),
    url(r'^lent/$', LentView.as_view(), name='lent'),
    url(r'^history/$', HistoryView.as_view(), name='history'),
    url(r'^return/$', ReturnView.as_view(), name='return'),
]

Final Project/Code/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from config import settings
from account.views import IndexView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^book/', include('book.urls', namespace='book')),
    url(r'^transaction/', include('transaction.urls', namespace='transaction')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Final Project/Code/templates/base.html
{% load i18n static %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}" />
    {% block extrastyle %}{% endblock %}
    {% if LANGUAGE_BIDI %}
        <link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}"/>
    {% endif %}

    {% block extrahead %}{% endblock %}

    {% block responsive %}
        <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive.css" %}" />
        {% if LANGUAGE_BIDI %}
            <link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive_rtl.css" %}" />
        {% endif %}
    {% endblock %}
    {% block blockbots %}
        <meta name="robots" content="NONE,NOARCHIVE" />
    {% endblock %}
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}" data-admin-utc-offset="{% now "Z" %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
        <!-- Header -->
        <div id="header">
            <div id="branding">
                {% block branding %}{% endblock %}
            </div>
            {% block usertools %}
            {% if user.is_authenticated %}
                <div id="user-tools">
                    {% block welcome-msg %}
                        {% trans 'Welcome,' %}
                        <strong>{% firstof user.get_short_name user.get_username %}</strong>.
                    {% endblock %}
                    {% block userlinks %}
                        {% if site_url %}
                            <a href="{{ site_url }}">{% trans 'View site' %}</a> /
                        {% endif %}
                        {% if user.is_active and user.is_staff %}
                            {% url 'django-admindocs-docroot' as docsroot %}
                            {% if docsroot %}
                                <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                            {% endif %}
                        {% endif %}
<!--                         {% if user.has_usable_password %}
                        <a href="{% url 'admin:password_change' %}">{% trans 'Change password' %}</a> /
                        {% endif %}
 -->                        <a href="{% url 'account:logout' %}">{% trans 'Log out' %}</a>
                    {% endblock %}
                </div>
            {% endif %}
            {% endblock %}
            {% block nav-global %}{% endblock %}
        </div>
        <!-- END Header -->

        {% block breadcrumbs %}
            <div class="breadcrumbs">
                <a href="{% url 'index' %}">{% trans 'Home' %}</a>
                <a href="{% url 'account:issue_borrowing_card' %}">{% trans 'IssueBorrowingCardView' %}</a>
                <a href="{% url 'account:activate_borrowing_card' %}">{% trans 'ActivateBorrowingCardView' %}</a>
                <a href="{% url 'book:register' %}">{% trans 'Register book' %}</a>
                <a href="{% url 'book:search' %}">{% trans 'Search books' %}</a>
                <a href="{% url 'book:copy' %}">{% trans 'Copies info' %}</a>
                <a href="{% url 'transaction:cart' %}">{% trans 'View cart' %}</a>
                <a href="{% url 'transaction:check_out' %}">{% trans 'Check out' %}</a>
                <a href="{% url 'transaction:borrow' %}">{% trans 'View borrow' %}</a>
                <a href="{% url 'transaction:lent' %}">{% trans 'Lent' %}</a>
                <a href="{% url 'transaction:history' %}">{% trans 'History' %}</a>
                <a href="{% url 'transaction:return' %}">{% trans 'Return' %}</a>
            </div>
        {% endblock %}

    {% endif %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colL{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

</body>
</html>

Final Project/Code/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h2>Welcome to library</h2>
{% endblock content %}